# db.yaml
mysql:
  config:
    host: "127.0.0.1"
    port: 3306
    user: "Lennon"
    password: "123456"
    database: "jeecg-boot"

  parameters:
    pool_size: 5
    charset: "utf8"

  fileds:
    course_cols:
      - cno
      - cname
      - ccredit
      - cdept